# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 19:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelikauppa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameownerships',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
