# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelikauppa', '0003_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameownerships',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
